const types = {
  WATCH_SEARCH_USERS: 'WATCH_SEARCH_USERS',
  WATCH_GET_USERS: 'WATCH_GET_USERS',
  WATCH_SET_USERS: 'WATCH_SET_USERS',
  SET_USERS: 'SET_USERS',

  WATCH_GET_PROFILE: 'WATCH_GET_PROFILE',
  SET_PROFILE: 'SET_PROFILE',
  WATCH_GET_REPOS: 'WATCH_GET_REPOS',
  SET_REPOS: 'SET_REPOS',

  WATCH_ADD_NOTIFICATION: 'WATCH_SET_NOTIFICATION',
  ADD_NOTIFICATION: 'ADD_NOTIFICATION',
  WATCH_REM_NOTIFICATION: 'WATCH_REM_NOTIFICATION',
  REM_NOTIFICATION: 'REM_NOTIFICATION',
};

export default types;
